-- Auto-generated from 'MC Guest List.xlsx' on 2026-05-03.
-- Insert is idempotent (ON CONFLICT DO NOTHING) — safe to re-run.
-- 72 invitations, 81 total people invited (7 with +1, 1 with +2).

insert into guests (wedding_slug, token, full_name, party_size) values
  ('craig-and-monique', 'craig-batson', 'Craig Batson', 1),
  ('craig-and-monique', 'monique-christian', 'Monique Christian', 1),
  ('craig-and-monique', 'andrea-agarratt-joseph', 'Andrea Agarratt-Joseph', 1),
  ('craig-and-monique', 'cassandra-bobb', 'Cassandra Bobb', 1),
  ('craig-and-monique', 'lee-andra-batson', 'Lee-andra Batson', 1),
  ('craig-and-monique', 'bernice-samuel', 'Bernice Samuel', 1),
  ('craig-and-monique', 'joshua-daniel', 'Joshua Daniel', 1),
  ('craig-and-monique', 'javal-joseph', 'Javal Joseph', 1),
  ('craig-and-monique', 'ayodele-gabriel', 'Ayodele Gabriel', 1),
  ('craig-and-monique', 'akil-hosang', 'Akil Hosang', 2),
  ('craig-and-monique', 'kayla-ross', 'Kayla Ross', 1),
  ('craig-and-monique', 'makesi-broomes', 'Makesi Broomes', 1),
  ('craig-and-monique', 'shania-pierre', 'Shania Pierre', 1),
  ('craig-and-monique', 'larnel-roberts', 'Larnel Roberts', 1),
  ('craig-and-monique', 'stevie-ann-gomez', 'Stevie-Ann Gomez', 1),
  ('craig-and-monique', 'dylan-samuel', 'Dylan Samuel', 1),
  ('craig-and-monique', 'allan-adimoolah', 'Allan Adimoolah', 1),
  ('craig-and-monique', 'kimberly-adimoolah', 'Kimberly Adimoolah', 1),
  ('craig-and-monique', 'amrun-adimoolah', 'Amrun Adimoolah', 1),
  ('craig-and-monique', 'rennie-st-hill', 'Rennie St. Hill', 1),
  ('craig-and-monique', 'joy-st-hill', 'Joy St. Hill', 1),
  ('craig-and-monique', 'cherry-ann-daniel', 'Cherry-Ann Daniel', 1),
  ('craig-and-monique', 'sharaz-daniel', 'Sharaz Daniel', 1),
  ('craig-and-monique', 'jaynee-john', 'Jaynee John', 2),
  ('craig-and-monique', 'michelle-scipio-hosang', 'Michelle Scipio-Hosang', 1),
  ('craig-and-monique', 'nicolette-christian', 'Nicolette Christian', 1),
  ('craig-and-monique', 'dominic-romeo', 'Dominic Romeo', 1),
  ('craig-and-monique', 'levi-romeo', 'Levi Romeo', 1),
  ('craig-and-monique', 'niel-christian', 'Niel Christian', 1),
  ('craig-and-monique', 'alexia-ashton-marin', 'Alexia Ashton-Marin', 1),
  ('craig-and-monique', 'giselle-ollivierre-christian', 'Giselle Ollivierre-Christian', 1),
  ('craig-and-monique', 'himraj-christian', 'Himraj Christian', 1),
  ('craig-and-monique', 'karena-jagan', 'Karena Jagan', 1),
  ('craig-and-monique', 'zackery-jaimungal', 'Zackery Jaimungal', 1),
  ('craig-and-monique', 'krysta-jagan-ramroop', 'Krysta Jagan-Ramroop', 1),
  ('craig-and-monique', 'cody-ramroop', 'Cody Ramroop', 1),
  ('craig-and-monique', 'sara-martinez', 'Sara Martinez', 1),
  ('craig-and-monique', 'jesse-mahabir', 'Jesse Mahabir', 1),
  ('craig-and-monique', 'janelle-ollivierre-farmer', 'Janelle Ollivierre-Farmer', 1),
  ('craig-and-monique', 'angelo-farmer', 'Angelo Farmer', 1),
  ('craig-and-monique', 'nichelle-ollivierre', 'Nichelle Ollivierre', 2),
  ('craig-and-monique', 'mickel-romany', 'Mickel Romany', 1),
  ('craig-and-monique', 'nyka-romany', 'Nyka Romany', 1),
  ('craig-and-monique', 'miciaus-romany', 'Miciaus Romany', 1),
  ('craig-and-monique', 'angilo-ollivierre', 'Angilo Ollivierre', 1),
  ('craig-and-monique', 'shane-ollivierre', 'Shane Ollivierre', 1),
  ('craig-and-monique', 'nalini-ramnath', 'Nalini Ramnath', 1),
  ('craig-and-monique', 'roaudeatte-herbert', 'Roaudeatte Herbert', 1),
  ('craig-and-monique', 'asia-ollivierre', 'Asia Ollivierre', 1),
  ('craig-and-monique', 'wainwright-phillip', 'Wainwright Phillip', 1),
  ('craig-and-monique', 'joel-blackwood', 'Joel Blackwood', 1),
  ('craig-and-monique', 'vee-hughes', 'Vee Hughes', 1),
  ('craig-and-monique', 'berlina-williams-batson', 'Berlina Williams-Batson', 1),
  ('craig-and-monique', 'carl-batson', 'Carl Batson', 1),
  ('craig-and-monique', 'brenda-henry', 'Brenda Henry', 3),
  ('craig-and-monique', 'kalliser-williams', 'Kalliser Williams', 1),
  ('craig-and-monique', 'andy-williams', 'Andy Williams', 2),
  ('craig-and-monique', 'selwyn-cudjoe', 'Selwyn Cudjoe', 1),
  ('craig-and-monique', 'margaret-cudjoe', 'Margaret Cudjoe', 1),
  ('craig-and-monique', 'jael-cudjoe', 'Jael Cudjoe', 1),
  ('craig-and-monique', 'terrel-cudjoe', 'Terrel Cudjoe', 1),
  ('craig-and-monique', 'justin-fournillier', 'Justin Fournillier', 1),
  ('craig-and-monique', 'joseph-dennis', 'Joseph Dennis', 2),
  ('craig-and-monique', 'jeron-paul', 'Jeron Paul', 1),
  ('craig-and-monique', 'jeremy-hosein', 'Jeremy Hosein', 2),
  ('craig-and-monique', 'jessie-williams', 'Jessie Williams', 2),
  ('craig-and-monique', 'jim-daniel', 'Jim Daniel', 1),
  ('craig-and-monique', 'laura-daniel', 'Laura Daniel', 1),
  ('craig-and-monique', 'lindy-christmas', 'Lindy Christmas', 1),
  ('craig-and-monique', 'dane-christmas', 'Dane Christmas', 1),
  ('craig-and-monique', 'lester-brown', 'Lester Brown', 1),
  ('craig-and-monique', 'myrtle-brown', 'Myrtle Brown', 1)
on conflict (token) do nothing;

